/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author RONNY PANTOJA
 */
public class AlquilarFinal extends javax.swing.JFrame {

    /**
     * Creates new form AlquilarFinal
     */
    public AlquilarFinal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_aviones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Btn_buscar = new javax.swing.JButton();
        Txt_matricula = new javax.swing.JTextField();
        Btn_alquilar = new javax.swing.JButton();
        Btn_registrar = new javax.swing.JButton();
        Btn_refrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tbl_aviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matricula ", "Alto", "Largo", "Ancho", "ID cliente", "Estado"
            }
        ));
        Tbl_aviones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_avionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_aviones);

        jLabel1.setText("MATRICULA DE AVION");

        Btn_buscar.setText("BUSCAR");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        Txt_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_matriculaActionPerformed(evt);
            }
        });

        Btn_alquilar.setText("ALQUILAR");

        Btn_registrar.setText("REGISTRAR");
        Btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_registrarActionPerformed(evt);
            }
        });

        Btn_refrescar.setText("REFRESCAR");
        Btn_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_refrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(Txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_refrescar)
                        .addGap(37, 37, 37)
                        .addComponent(Btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_alquilar)
                        .addGap(39, 39, 39)
                        .addComponent(Btn_registrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_alquilar)
                    .addComponent(Btn_buscar)
                    .addComponent(Btn_registrar)
                    .addComponent(Btn_refrescar))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_matriculaActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_buscarActionPerformed

    private void Btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_registrarActionPerformed

    private void Btn_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_refrescarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_refrescarActionPerformed

    private void Tbl_avionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_avionesMouseClicked
        
        int seleccion = Tbl_aviones.rowAtPoint(evt.getPoint());
        Txt_matricula.setText(String.valueOf(Tbl_aviones.getValueAt(seleccion, 0)));
    }//GEN-LAST:event_Tbl_avionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlquilarFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlquilarFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlquilarFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlquilarFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlquilarFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_alquilar;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_refrescar;
    private javax.swing.JButton Btn_registrar;
    private javax.swing.JTable Tbl_aviones;
    private javax.swing.JTextField Txt_matricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_alquilar() {
        return Btn_alquilar;
    }

    public void setBtn_alquilar(JButton Btn_alquilar) {
        this.Btn_alquilar = Btn_alquilar;
    }

    public JButton getBtn_buscar() {
        return Btn_buscar;
    }

    public void setBtn_buscar(JButton Btn_buscar) {
        this.Btn_buscar = Btn_buscar;
    }

    public JButton getBtn_registrar() {
        return Btn_registrar;
    }

    public void setBtn_registrar(JButton Btn_registrar) {
        this.Btn_registrar = Btn_registrar;
    }

    public JTable getTbl_aviones() {
        return Tbl_aviones;
    }

    public void setTbl_aviones(JTable Tbl_aviones) {
        this.Tbl_aviones = Tbl_aviones;
    }

    public JTextField getTxt_matricula() {
        return Txt_matricula;
    }

    public void setTxt_matricula(JTextField Txt_matricula) {
        this.Txt_matricula = Txt_matricula;
    }

    public JButton getBtn_refrescar() {
        return Btn_refrescar;
    }

    public void setBtn_refrescar(JButton Btn_refrescar) {
        this.Btn_refrescar = Btn_refrescar;
    }

    
    
    


}
