/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Toolkit;
import javax.swing.JButton;

/**
 *
 * @author julia
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icono/icono.png")));
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btn_hangar = new javax.swing.JButton();
        Btn_cliente = new javax.swing.JButton();
        Btn_alquilar = new javax.swing.JButton();
        Btn_ConsultarHangar = new javax.swing.JButton();
        Btn_ConsultarCliente = new javax.swing.JButton();
        Btn_ConsultarAvion = new javax.swing.JButton();
        Btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ADMINISTRACION DE HANGARES");

        Btn_hangar.setText("REGISTRAR NUEVO HANGAR");
        Btn_hangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_hangarActionPerformed(evt);
            }
        });

        Btn_cliente.setText("REGISTRAR NUEVO CLIENTE");
        Btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_clienteActionPerformed(evt);
            }
        });

        Btn_alquilar.setText("ALQUILAR HANGAR");

        Btn_ConsultarHangar.setText("CONSULTAR HANGAR");
        Btn_ConsultarHangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConsultarHangarActionPerformed(evt);
            }
        });

        Btn_ConsultarCliente.setText("CONSULTAR CLIENTE");

        Btn_ConsultarAvion.setText("CONSULTAR AVIONES");
        Btn_ConsultarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConsultarAvionActionPerformed(evt);
            }
        });

        Btn_cancelar.setText("CANCELAR ALQUILER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Btn_alquilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_hangar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_ConsultarHangar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_ConsultarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_ConsultarAvion, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(Btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_hangar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ConsultarHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_ConsultarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_alquilar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(Btn_ConsultarAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_hangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_hangarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_hangarActionPerformed

    private void Btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_clienteActionPerformed

    private void Btn_ConsultarHangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConsultarHangarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ConsultarHangarActionPerformed

    private void Btn_ConsultarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConsultarAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ConsultarAvionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ConsultarAvion;
    private javax.swing.JButton Btn_ConsultarCliente;
    private javax.swing.JButton Btn_ConsultarHangar;
    private javax.swing.JButton Btn_alquilar;
    private javax.swing.JButton Btn_cancelar;
    private javax.swing.JButton Btn_cliente;
    private javax.swing.JButton Btn_hangar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_alquilar() {
        return Btn_alquilar;
    }

    public void setBtn_alquilar(JButton Btn_alquilar) {
        this.Btn_alquilar = Btn_alquilar;
    }

    public JButton getBtn_cliente() {
        return Btn_cliente;
    }

    public void setBtn_cliente(JButton Btn_cliente) {
        this.Btn_cliente = Btn_cliente;
    }

    public JButton getBtn_hangar() {
        return Btn_hangar;
    }

    public void setBtn_hangar(JButton Btn_hangar) {
        this.Btn_hangar = Btn_hangar;
    }

    public JButton getBtn_cancelar() {
        return Btn_cancelar;
    }

    public void setBtn_cancelar(JButton Btn_cancelar) {
        this.Btn_cancelar = Btn_cancelar;
    }

    public JButton getBtn_ConsultarAvion() {
        return Btn_ConsultarAvion;
    }

    public void setBtn_ConsultarAvion(JButton Btn_ConsultarAvion) {
        this.Btn_ConsultarAvion = Btn_ConsultarAvion;
    }

    public JButton getBtn_ConsultarCliente() {
        return Btn_ConsultarCliente;
    }

    public void setBtn_ConsultarCliente(JButton Btn_ConsultarCliente) {
        this.Btn_ConsultarCliente = Btn_ConsultarCliente;
    }

    public JButton getBtn_ConsultarHangar() {
        return Btn_ConsultarHangar;
    }

    public void setBtn_ConsultarHangar(JButton Btn_ConsultarHangar) {
        this.Btn_ConsultarHangar = Btn_ConsultarHangar;
    }
    
    
    
    


}
